spring.application.name=RecyQ


# server í¬í¸ë²í¸ ë±ë¡
server.port = 8087


# context-path ë±ë¡
server.servlet.context-path=/recyq


# DBì ë³´ ë±ë¡
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ieum
spring.datasource.username=com
spring.datasource.password=1234


# DBë¬¸ë² ì¬ì© ì¤ì 
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# íì´ë¸ ìì± ë° ìë°ì´í¸
spring.jpa.hibernate.ddl-auto=create


# ìì±ëë sqlêµ¬ë¬¸ ì¶ë ¥
spring.jpa.show-sql=true


# sqlêµ¬ë¬¸ì ê°ëì± ì¢ê² ì¶ë ¥
spring.jpa.properties.hibernate.format_sql=true




